[theme]
# Primary accent for interactive elements
primaryColor = '#404a33'

# Background color for the main content area
backgroundColor = '#f9faef'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#dce7c8'

# Color used for almost all text
textColor = '#1f3701'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"
